# Generated by Django 4.2.3 on 2023-07-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_post_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='home',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
        migrations.AddField(
            model_name='content',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost'),
        ),
    ]
