# Generated by Django 4.2.3 on 2023-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_content_remove_blogpost_home_remove_blogpost_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
